name: Rust Build and Test

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust Version
        run: rustc --version
      - name: Run cargo build (default)
        run: cargo build --release
      - name: Run cargo build (--all-features)
        run: cargo build --release --all-features
      - name: Run cargo build (--no-default-features)
        run: cargo build --release --no-default-features
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Rust Version
        run: rustc --version
      - name: Run cargo check (--all-features)
        run: cargo check --all-features
      - name: Run cargo test (default)
        run: cargo test
      - name: Run cargo test (--all-features)
        run: cargo test --all-features
      - name: Run cargo test (--no-default-features)
        run: cargo test --no-default-features
